# .github/workflows/deploy.yml

name: 'Terragrunt Deploy'
  
on:
  push:
    paths:
      - '.github/**'
      - 'modules/**'
      - 'infra/**'
      - 'justfile'
      - 'go.mod'
   
jobs:
  Pre-check:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
            
  Build-lambdas:
    name: 'Build Go lambda'
    needs: Pre-check
    uses: fomiller/gh-actions/.github/workflows/go-lambda.yaml@main
    with:
      lambda_src: infra/modules/aws/lambda/src/main.go
      lambda_output:  infra/modules/aws/lambda/bin/lambda_congocoon
      artifacts_dir: infra/modules/aws/lambda/src/bin
        
  Deploy-infra:
    name: 'Deploy Infra'
    needs: [Build-Lambdas]
    uses: fomiller/gh-actions/.github/workflows/terragrunt.yaml@main
    with:
      environment: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref) && 'prod' || 'dev' }}
      infra-dir: infra/modules/aws
      doppler-project: congocoon-lambda
      download-artifacts: true
      artifacts_dir: infra/modules/aws/lambda/src/bin
    secrets: inherit
        
    # use if you need to debug workflow
    # - name: DEBUG
    #   uses: lhotari/action-upterm@v1
    #   with:
    #       limit-access-to-actor: true
    #       limit-access-to-users: Fomiller

